### ISSUE TITLE
scale_range in postprocessing

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/core-bioimage-io-python#127]
@esgomezm  and me are debugging a [zero cost model](https://sandbox.zenodo.org/record/938151) that has `scale_range` in postprocessing:
```yaml
  - name: scale_range
    kwargs:
      mode: per_sample
      axes: xyzc
      min_percentile: 0
      max_percentile: 100 
```
According [to the spec](https://github.com/bioimage-io/spec-bioimage-io/blob/main/supported_formats_and_operations.md#postprocessing) this should be valid (i.e. `reference_tensor` is  not defined, so the tensor itself should be used).

However, when running the model the following error is thrown:
```
(bio-core-dev) pape@mokshi:~/Work/bioimageio/use-cases/zero-cost$ bioimageio test-model unet-no-thresh/model.yaml
Traceback (most recent call last):
  File "/home/pape/Work/software/conda/miniconda3/envs/bio-core-dev/bin/bioimageio", line 33, in <module>
    sys.exit(load_entry_point('bioimageio.core', 'console_scripts', 'bioimageio')())
  File "/home/pape/Work/software/conda/miniconda3/envs/bio-core-dev/lib/python3.7/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/home/pape/Work/software/conda/miniconda3/envs/bio-core-dev/lib/python3.7/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/pape/Work/software/conda/miniconda3/envs/bio-core-dev/lib/python3.7/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/pape/Work/software/conda/miniconda3/envs/bio-core-dev/lib/python3.7/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/pape/Work/software/conda/miniconda3/envs/bio-core-dev/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pape/Work/software/conda/miniconda3/envs/bio-core-dev/lib/python3.7/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/pape/Work/software/conda/miniconda3/envs/bio-core-dev/lib/python3.7/site-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "/home/pape/Work/bioimageio/python-bioimage-io/bioimageio/core/__main__.py", line 55, in test_model
    test_passed = prediction.test_model(model_rdf, weight_format=weight_format, devices=devices, decimal=decimal)
  File "/home/pape/Work/bioimageio/python-bioimage-io/bioimageio/core/prediction.py", line 487, in test_model
    bioimageio_model=model, devices=devices, weight_format=weight_format
  File "/home/pape/Work/bioimageio/python-bioimage-io/bioimageio/core/prediction_pipeline/_prediction_pipeline.py", line 146, in create_prediction_pipeline
    processing = CombinedProcessing(bioimageio_model.inputs, bioimageio_model.outputs)
  File "/home/pape/Work/bioimageio/python-bioimage-io/bioimageio/core/prediction_pipeline/_combined_processing.py", line 76, in __init__
    raise NotImplementedError("computing statistics for output tensors not yet implemented")
NotImplementedError: computing statistics for output tensors not yet implemented

```

**Comment by FynnBe** [comment]
looks like the default "self" is not implemented yet. I will fix that...
