### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by uschmidt83** [bioimage-io/core-bioimage-io-python#217]
```python
$ pip list | grep bioimage
bioimageio.core        0.4.10
bioimageio.spec        0.3.4.post0

$ python -c "from bioimageio.core.build_spec import build_model"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/uwe/sw/miniconda3/envs/tf1/lib/python3.7/site-packages/bioimageio/core/__init__.py", line 6, in <module>
    from .resource_io import (
  File "/home/uwe/sw/miniconda3/envs/tf1/lib/python3.7/site-packages/bioimageio/core/resource_io/__init__.py", line 2, in <module>
    from .io_ import (
  File "/home/uwe/sw/miniconda3/envs/tf1/lib/python3.7/site-packages/bioimageio/core/resource_io/io_.py", line 10, in <module>
    from bioimageio.core.resource_io.nodes import ResourceDescription
  File "/home/uwe/sw/miniconda3/envs/tf1/lib/python3.7/site-packages/bioimageio/core/resource_io/nodes.py", line 11, in <module>
    from bioimageio.spec.collection import raw_nodes as collection_raw_nodes
ModuleNotFoundError: No module named 'bioimageio.spec.collection'
```

**Comment by uschmidt83** [comment]
Seems that `install_requires=["bioimageio.spec>=0.3.4", ...],` is outdated and requires never version of spec.

https://github.com/bioimage-io/core-bioimage-io-python/blob/67a1264d86f96418b9131142c26374c8913e0214/setup.py#L28

**Comment by FynnBe** [comment]
thanks for raising this issue 👍

**Comment by uschmidt83** [comment]
It happened again:

```python
$ pip list | grep bioimage
bioimageio.core        0.5.0
bioimageio.spec        0.4.3

$ python -c "from bioimageio.core.build_spec import build_model"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/uwe/sw/miniconda3/envs/tf1/lib/python3.7/site-packages/bioimageio/core/__init__.py", line 6, in <module>
    from .resource_io import (
  File "/home/uwe/sw/miniconda3/envs/tf1/lib/python3.7/site-packages/bioimageio/core/resource_io/__init__.py", line 2, in <module>
    from .io_ import (
  File "/home/uwe/sw/miniconda3/envs/tf1/lib/python3.7/site-packages/bioimageio/core/resource_io/io_.py", line 16, in <module>
    from .utils import resolve_raw_resource_description, resolve_source
  File "/home/uwe/sw/miniconda3/envs/tf1/lib/python3.7/site-packages/bioimageio/core/resource_io/utils.py", line 9, in <module>
    from bioimageio.spec.shared import raw_nodes, resolve_source, source_available
ImportError: cannot import name 'resolve_source' from 'bioimageio.spec.shared' (/home/uwe/sw/miniconda3/envs/tf1/lib/python3.7/site-packages/bioimageio/spec/shared/__init__.py)
```

**Comment by uschmidt83** [comment]
This time needs `"bioimageio.spec>=0.4.4"`.

https://github.com/bioimage-io/core-bioimage-io-python/blob/e9da41caa2bb24ea78d4516ae678b29cb133e5b2/setup.py#L28

**Comment by FynnBe** [comment]
yeah.. we really need to automate this eventually!
