### ISSUE TITLE
'InputTensor' object has no attribute 'root_path'

### ISSUE THREAD

**Issue by oeway** [bioimage-io/core-bioimage-io-python#285]
Hi @FynnBe I am trying the fix for supporting raw nodes: https://github.com/bioimage-io/core-bioimage-io-python/pull/284

However, it doesn't seem to work:

```
AssertionError: Traceback (most recent call last):
  File "/models/bioengine-model-runner/1/model.py", line 146, in execute
    pred_pipeline = create_prediction_pipeline(
  File "/tmp/python_env_c4AXyh/0/lib/python3.8/site-packages/bioimageio/core/prediction_pipeline/_prediction_pipeline.py", line 213, in create_prediction_pipeline
    ipts = [resolve_raw_node(s, nodes) for s in bioimageio_model.inputs]
  File "/tmp/python_env_c4AXyh/0/lib/python3.8/site-packages/bioimageio/core/prediction_pipeline/_prediction_pipeline.py", line 213, in <listcomp>
    ipts = [resolve_raw_node(s, nodes) for s in bioimageio_model.inputs]
  File "/tmp/python_env_c4AXyh/0/lib/python3.8/site-packages/bioimageio/core/resource_io/utils.py", line 111, in resolve_raw_node
    rd = UriNodeTransformer(root_path=raw_rd.root_path, uri_only_if_in_package=uri_only_if_in_package).transform(raw_rd)
AttributeError: 'InputTensor' object has no attribute 'root_path'
```

I am not sure what your note mean when you say override the _prepare model function, but I did this: 
```python
class TritonModelAdapter(ModelAdapter):
    @staticmethod
    def _prepare_model(bioimageio_model):
        return bioimageio_model
```

And here is how I run it:
```python
    model_resource = bioimageio.core.load_raw_resource_description(model_id)
    pred_pipeline = create_prediction_pipeline(
        bioimageio_model=model_resource,
        model_adapter=TritonModelAdapter(
             ...
            model_resource=model_resource,
        ),
    )
```

Note, the goal is to avoid downloading all the weights files for a model, we simply need the id and pre/post processing.

**Comment by oeway** [comment]
Update: I fixed it by doing the following before calling `create_prediction_pipeline `:

```python
                        for s in model_resource.inputs:
                            s.root_path =  model_resource.root_path
                        for s in model_resource.outputs:
                            s.root_path =  model_resource.root_path
```
