### ISSUE TITLE
New predict command: axis naming is inconsistent

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/core-bioimage-io-python#412]
The axis naming between input tensors in the model and the names expected by the predict function is currently inconsistent.

The following code fails with an error (see full backtrace below), because it expects the axis names `batch` and `channel` instead of `b` and `c`. However, the corresponding axes are called `b` and `c` in the model tensors. This makes everything inconsistent and it's not possible to derive the axis names from the model description in code.

```python
import bioimageio.core
import imageio.v3 as imageio
from xarray import DataArray

# For a reproducible example you can use the model test inputs.
# (I cannot easily figure out how to load them from the model ...)
image = imageio.imread("/home/pape/.cache/micro_sam/sample_data/livecell-2d-image.png")
model = bioimageio.core.load_description("hiding-tiger")

print(model.inputs[0].axes)
# prints bcyx

inputs = {model.inputs[0].name: DataArray(image[None, None], dims=("b", "c", "y", "x"))}

# prediction with tiling
pred = bioimageio.core.predict(model=model, inputs=inputs)
```

it works with `inputs = {model.inputs[0].name: DataArray(image[None, None], dims=("batch", "channel", "y", "x"))}`

Error:
```
Traceback (most recent call last):
  File "/home/pape/Work/playground/bioimageio/new-pred/check_new_pred.py", line 15, in <module>
    pred = bioimageio.core.predict(model=model, inputs=inputs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pape/Work/bioimageio/core-bioimage-io-python/bioimageio/core/prediction.py", line 114, in predict
    output = pp.predict_sample_without_blocking(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pape/Work/bioimageio/core-bioimage-io-python/bioimageio/core/_prediction_pipeline.py", line 153, in predict_sample_without_blocking
    self.apply_preprocessing(sample)
  File "/home/pape/Work/bioimageio/core-bioimage-io-python/bioimageio/core/_prediction_pipeline.py", line 289, in apply_preprocessing
    op(sample)
  File "/home/pape/Work/bioimageio/core-bioimage-io-python/bioimageio/core/proc_ops.py", line 188, in __call__
    sample.stat.update(self.stats_calculator.update_and_get_all(origin))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pape/Work/bioimageio/core-bioimage-io-python/bioimageio/core/stat_calculators.py", line 441, in update_and_get_all
    return {**self._compute(last_sample), **self.finalize()}
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pape/Work/bioimageio/core-bioimage-io-python/bioimageio/core/stat_calculators.py", line 450, in _compute
    values = calc.compute(sample)
             ^^^^^^^^^^^^^^^^^^^^
  File "/home/pape/Work/bioimageio/core-bioimage-io-python/bioimageio/core/stat_calculators.py", line 133, in compute
    mean = tensor.mean(dim=self._axes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pape/Work/bioimageio/core-bioimage-io-python/bioimageio/core/tensor.py", line 286, in mean
    return self.__class__.from_xarray(self._data.mean(dim=dim))
                                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pape/micromamba/envs/main/lib/python3.11/site-packages/xarray/core/_aggregations.py", line 1663, in mean
    return self.reduce(
           ^^^^^^^^^^^^
  File "/home/pape/micromamba/envs/main/lib/python3.11/site-packages/xarray/core/dataarray.py", line 3776, in reduce
    var = self.variable.reduce(func, dim, axis, keep_attrs, keepdims, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pape/micromamba/envs/main/lib/python3.11/site-packages/xarray/core/variable.py", line 1756, in reduce
    result = super().reduce(
             ^^^^^^^^^^^^^^^
  File "/home/pape/micromamba/envs/main/lib/python3.11/site-packages/xarray/namedarray/core.py", line 759, in reduce
    axis = self.get_axis_num(dim)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pape/micromamba/envs/main/lib/python3.11/site-packages/xarray/namedarray/core.py", line 659, in get_axis_num
    return tuple(self._get_axis_num(d) for d in dim)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pape/micromamba/envs/main/lib/python3.11/site-packages/xarray/namedarray/core.py", line 659, in <genexpr>
    return tuple(self._get_axis_num(d) for d in dim)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/pape/micromamba/envs/main/lib/python3.11/site-packages/xarray/namedarray/core.py", line 668, in _get_axis_num
    raise ValueError(f"{dim!r} not found in array dimensions {self.dims!r}")
ValueError: 'channel' not found in array dimensions ('b', 'c', 'y', 'x')
```

**Comment by FynnBe** [comment]
yeah, we should not convert axis like strings as if they are default values from model 0.4 to what would have been the default value of model 0.5.
Not sure what I was thinking there tbh... 
Fixed in [bc98d65](https://github.com/bioimage-io/core-bioimage-io-python/pull/406/commits/bc98d65ef6fd51524a98d2129bbddecef663a85e)

**Comment by constantinpape** [comment]
It still doesn't work for me after pulling `predict-cmd`

**Comment by FynnBe** [comment]
yes, also [5a9c1c7](https://github.com/bioimage-io/core-bioimage-io-python/pull/406/commits/5a9c1c733812c8acb048d43a461d902279678469) was needed where the same conversion happened for the processing operators.
now it works (tested with [2ec9e9e](https://github.com/bioimage-io/core-bioimage-io-python/pull/406/commits/2ec9e9e9ec97ba0b0ae8e79f1f026abef78a7ad7))
