### ISSUE TITLE
New predict command: normalization not applied?

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/core-bioimage-io-python#413]
Prediction with the code below fails with a datatype error that looks to me like the input is not correctly converted to float.
However, this model contains a normalization function in preprocessing. Is this maybe not correctly applied / is something else going wrong?

```python
import bioimageio.core
import imageio.v3 as imageio
from xarray import DataArray

# For a reproducible example you can use the model test inputs.
# (I cannot easily figure out how to load them from the model ...)
image = imageio.imread("/home/pape/.cache/micro_sam/sample_data/livecell-2d-image.png")
model = bioimageio.core.load_description("hiding-tiger")

inputs = {model.inputs[0].name: DataArray(image[None, None], dims=("batch", "channel", "y", "x"))}

# prediction with tiling
pred = bioimageio.core.predict(model=model, inputs=inputs)
```

Error:
```
Traceback (most recent call last):
  File "/home/pape/Work/playground/bioimageio/new-pred/check_new_pred.py", line 13, in <module>
    pred = bioimageio.core.predict(model=model, inputs=inputs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pape/Work/bioimageio/core-bioimage-io-python/bioimageio/core/prediction.py", line 114, in predict
    output = pp.predict_sample_without_blocking(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pape/Work/bioimageio/core-bioimage-io-python/bioimageio/core/_prediction_pipeline.py", line 160, in predict_sample_without_blocking
    self._adapter.forward(
  File "/home/pape/Work/bioimageio/core-bioimage-io-python/bioimageio/core/model_adapters/_pytorch_model_adapter.py", line 71, in forward
    result = self._network(  # pyright: ignore[reportUnknownVariableType]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pape/micromamba/envs/main/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pape/micromamba/envs/main/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pape/.cache/bioimageio/ece236f307012bdb3c878565fa94080e-unet.py", line 206, in forward
    return self._apply_default(x)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pape/.cache/bioimageio/ece236f307012bdb3c878565fa94080e-unet.py", line 169, in _apply_default
    x, encoder_out = self.encoder(x)
                     ^^^^^^^^^^^^^^^
  File "/home/pape/micromamba/envs/main/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pape/micromamba/envs/main/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pape/.cache/bioimageio/ece236f307012bdb3c878565fa94080e-unet.py", line 265, in forward
    x = block(x)
        ^^^^^^^^
  File "/home/pape/micromamba/envs/main/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pape/micromamba/envs/main/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pape/.cache/bioimageio/ece236f307012bdb3c878565fa94080e-unet.py", line 384, in forward
    return self.block(x)
           ^^^^^^^^^^^^^
  File "/home/pape/micromamba/envs/main/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pape/micromamba/envs/main/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pape/micromamba/envs/main/lib/python3.11/site-packages/torch/nn/modules/container.py", line 219, in forward
    input = module(input)
            ^^^^^^^^^^^^^
  File "/home/pape/micromamba/envs/main/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pape/micromamba/envs/main/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pape/micromamba/envs/main/lib/python3.11/site-packages/torch/nn/modules/instancenorm.py", line 95, in forward
    return self._apply_instance_norm(input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pape/micromamba/envs/main/lib/python3.11/site-packages/torch/nn/modules/instancenorm.py", line 37, in _apply_instance_norm
    return F.instance_norm(
           ^^^^^^^^^^^^^^^^
  File "/home/pape/micromamba/envs/main/lib/python3.11/site-packages/torch/nn/functional.py", line 2556, in instance_norm
    return torch.instance_norm(
           ^^^^^^^^^^^^^^^^^^^^
RuntimeError: "batch_norm" not implemented for 'Byte'
```

**Comment by FynnBe** [comment]
there is an error in hiding tiger then:
it states that it's input has `data_type: uint8`
In a past version we have simply cast everything to float after any preprocessing step, but this was removed (and never compliant with the spec).

there is also no reason hiding tiger should accept uint8 only for preprocessing.
we can either add an `ensure_dtype` preprocessing or (which I think makes more sense in this case) change  hiding tiger's `data_dtype`, as the model evidently expects float32.

**Comment by constantinpape** [comment]
I see. This is probably due to the confusion of the data_type refering to the model input or the preprocessing input.
I agree that this is probably better fixed in the model. 
Adding `model.inputs[0].data_type = "float32"` does the trick for now.

**Comment by FynnBe** [comment]
I also updated hiding-tiger to version 1.1 were this is fixed  accordingly.
